### ISSUE TITLE
重启之后令牌失效

### ISSUE THREAD

**Issue by 1PercentSync** [wozulong/neo-api#2]
前端的数据都还在但是调用的时候
401: {"error":{"message":"无效的令牌 (request id: 673e379f-43aa-4127-b80e-8905d43f10da)","type":"new_api_error"}}
新建令牌之后正常
docker compose：
```
  neo-api:
    image: pengzhile/new-api:latest
    container_name: neo-api
    restart: unless-stopped
    command: --log-dir /app/logs
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - /root/docker-data/neo-api/data:/data
      - /root/docker-data/neo-api/logs:/app/logs
    environment:
      - TZ=America/Denver
      - SQL_DSN=root:123456@tcp(mysql:3306)/neo-api
      - REDIS_CONN_STRING=redis://redis
      - GLOBAL_API_RATE_LIMIT_ENABLE=false
      - GEMINI_VISION_MAX_IMAGE_NUM=-1
    depends_on:
      - redis
      - mysql
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped

  mysql:
    image: mysql:8.2
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: neo-api
    volumes:
      - /root/docker-data/neo-api/mysql_data:/var/lib/mysql
```
